steps:
  # Step 1: Download and install Terraform
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Install Terraform'
    entrypoint: 'sh'
    args: ['-c', 'terraform version']

  # Step 2: Initialize Terraform
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Init'
    entrypoint: 'sh'
    args: ['-c', 'terraform init']
    dir: './'  # Directory where your Terraform files are located

  # Step 3: Check and import existing resources
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Import'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Check if the resources are already in the state and remove if necessary
        if terraform state list | grep -q 'google_storage_bucket.terraform_state'; then
          echo "Removing existing resource from state: google_storage_bucket.terraform_state"
          terraform state rm google_storage_bucket.terraform_state
        fi
        if terraform state list | grep -q 'google_storage_bucket.cloudbuild_logs'; then
          echo "Removing existing resource from state: google_storage_bucket.cloudbuild_logs"
          terraform state rm google_storage_bucket.cloudbuild_logs
        fi

        # Import the resources
        echo "Importing resources..."
        terraform import google_storage_bucket.terraform_state projects/${PROJECT_ID}/buckets/state00011
        terraform import google_storage_bucket.cloudbuild_logs projects/${PROJECT_ID}/buckets/cloudbuild-logs-00011
    dir: './'  # Directory where your Terraform files are located
    waitFor: ['Terraform Init']

  # Step 4: Plan the Terraform deployment
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Plan'
    entrypoint: 'sh'
    args: ['-c', 'terraform plan -out=tfplan']
    dir: './'  # Directory where your Terraform files are located
    waitFor: ['Terraform Import']

  # Step 5: Apply the Terraform configuration
  - name: 'hashicorp/terraform:1.5.3'
    id: 'Terraform Apply'
    entrypoint: 'sh'
    args: ['-c', 'terraform apply -auto-approve tfplan']
    dir: './'  # Directory where your Terraform files are located
    waitFor: ['Terraform Plan']

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
