steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world:latest']

  # Step 3: Deploy to GKE using Helm
  - name: 'alpine/helm'
    args:
      - 'upgrade'
      - '--install'
      - 'hello-world'
      - './helm-chart'
      - '--set'
      - 'image.repository=gcr.io/$PROJECT_ID/hello-world'
      - '--set'
      - 'image.tag=latest'

  # Optional: Set environment variables for GKE cluster
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=infra1-gke-cluster'
