steps:
  # Step 1: Set up GKE authentication for the region.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Use the cloud-sdk image
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Authenticating with GKE in the region..."
        gcloud container clusters get-credentials infra1-gke-cluster --region us-central1 --project $PROJECT_ID

  # Step 2: Create the new namespace if it doesn't exist.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Creating namespace 'jenkins' if it doesn't exist..."
        kubectl get namespace jenkins || kubectl create namespace jenkins

  # Step 3: Deploy Jenkins using Helm in the specified namespace.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Use the cloud-sdk image
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing Helm..."
        curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        echo "Deploying Jenkins to GKE with Helm in the 'jenkins' namespace..."
        helm repo add jenkins https://charts.jenkins.io
        helm repo update
        helm upgrade --install jenkins jenkins/jenkins \
        --set controller.adminUser=admin \
        --set controller.adminPassword=adminpassword \
        --set controller.serviceType=LoadBalancer \
        --set controller.installPlugins='kubernetes:1.31.0,workflow-aggregator:2.6,git:5.0.1,docker-workflow:1.26,blueocean:1.24.5' \
        --namespace jenkins \
        --create-namespace
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=infra1-gke-cluster'

# Optional: Set the service account if necessary for specific permissions.
serviceAccount: "514264950628-compute@developer.gserviceaccount.com"

# Specify logs bucket for Cloud Build logs.
logsBucket: "gs://cloudbuild-logs-0111"  # Replace with your actual bucket name.
