# lloydsinterview/cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world:latest']

  # Step 3: Set up Helm and Kubernetes authentication
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['get', 'nodes']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'   # Set your GKE cluster zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=your-cluster-name'

  # Step 4: Deploy the application to GKE using Helm
  - name: 'gcr.io/cloud-builders/helm'
    args: ['upgrade', '--install', 'hello-world', './helm-chart',
           '--set', 'image.repository=gcr.io/$PROJECT_ID/hello-world',
           '--set', 'image.tag=latest']

images:
  - 'gcr.io/$PROJECT_ID/hello-world:latest'
