steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world:latest']

  # Step 3: Authenticate to GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'infra1-gke-cluster'
      - '--zone'
      - 'us-central1-a'    # Set the appropriate zone of your cluster
      - '--project'
      - '$PROJECT_ID'

  # Step 4: Verify kubectl connectivity by getting the nodes in the cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['get', 'nodes']

  # Step 5: Deploy the application to GKE using Helm
  - name: 'gcr.io/cloud-builders/helm'
    args:
      - 'upgrade'
      - '--install'
      - 'hello-world'     # Release name for the Helm deployment
      - './helm-chart'    # Path to your Helm chart directory
      - '--set'
      - 'image.repository=gcr.io/$PROJECT_ID/hello-world'
      - '--set'
      - 'image.tag=latest'

images:
  - 'gcr.io/$PROJECT_ID/hello-world:latest'

options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Logging enabled
timeout: '1200s'  # Set timeout to 20 minutes
