steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world:latest']

  # Step 3: Deploy to GKE using Helm
  - name: 'alpine/helm'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        helm upgrade --install hello-world ./helm-chart \
        --set image.repository=gcr.io/$PROJECT_ID/hello-world \
        --set image.tag=latest
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=infra1-gke-cluster'
      - 'PRIVATE_KEY=$$PRIVATE_KEY'
      - 'PUBLIC_KEY=$$PUBLIC_KEY'

# Optional: Set the service account (if needed)
serviceAccount: "jenkins@infra1-430721.iam.gserviceaccount.com"

# Specify logs bucket for Cloud Build logs
logsBucket: "gs://cloudbuild-logs-00111"  # Replace with your actual bucket name
