version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"             # Map host port 8080 to container port 8080
      - "50000:50000"           # Map host port 50000 to container port 50000 (for agents)
    volumes:
      - jenkins_home:/var/jenkins_home # Persist Jenkins data
    restart: unless-stopped     # Automatically restart the container unless stopped

volumes:
  jenkins_home:                 # Declare the Jenkins data volume
