apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
