# Namespace to deploy into
namespace: jenkins  # Ensure this matches your intended namespace

# Number of replicas
replicas: 1  # Typically, Jenkins runs as a single instance

# Image settings
image:
  repository: jenkins/jenkins  # Official Jenkins Docker image
  tag: lts  # Use the long-term support version

# Container port
containerPort: 8080  # Default port for Jenkins

# Resource limits and requests for the Jenkins container
resources:
  requests:
    memory: "256Mi"  # Minimum memory request
    cpu: "500m"      # Minimum CPU request
  limits:
    memory: "512Mi"   # Maximum memory limit
    cpu: "1"          # Maximum CPU limit
