# lloydsinterview/helm-chart/values.yaml
replicaCount: 2

image:
  repository: gcr.io/playground-s-11-206df3f9/hello-world
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}
