# lloydsinterview/helm-chart/values.yaml
replicaCount: 2

image:
  repository: gcr.io/infra1-430721/hello-world
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}
