apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer  # Use LoadBalancer to expose Jenkins externally
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80  # Expose port 80 for external access
      targetPort: {{ .Values.containerPort | default 8080 }}  # Forward to Jenkins port
